# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
lib_common_CELAGS_EXTRA := -m32 -fno-builtin\-I$(LIB_COMMON_DIR)
FLOAT_SRC :=$(LIB_COMMON_DIR)/FLOAT.c
$(FLOAT_OBJ):$(FLOAT_SRC)
	$(call make_command,$(CC),$(lib_common_CFLAGS_EXTRA),ld $@,$(CFLAGS)$(FLOAT_SRC))
